name: dqn_racing_conda
channels:
  - conda-forge
  - pytorch
  - defaults
dependencies:
  - python=3.8
  - pytorch>=2.0.0
  - torchvision>=0.15.0
  - box2d-py
  - gymnasium
  - pygame>=2.5.0
  - numpy>=1.24.0
  - matplotlib>=3.7.0
  - opencv
  - pillow>=10.0.0
  - scipy>=1.10.0
  - jupyter
  - notebook
  - pip
  - pip:
    - tensorboard>=2.13.0
    - tqdm>=4.65.0